### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by holly-hacker** [shaxxx/AltHttp#1]
The Dart SDK is licensed under the [3-clause BSD license](https://github.com/dart-lang/sdk/blob/master/LICENSE), which this repository currently doesn't follow since it simply relicenses the code under MIT. I'm not expert on licenses but at the very least a copy of the original BSD license should be included.

**Comment by shaxxx** [comment]
Thanks for the issue, I'll take care of it ASAP. 
Regards.

**Comment by shaxxx** [comment]
Replaced LICENSE file with original from Dart project. Hopefully this should do.
I'm gonna leave this open for a while if someone else has additional tips.
Thanks @HoLLy-HaCKeR

**Comment by shaxxx** [comment]
Considering this done
