### ISSUE TITLE
How to initialize AltHttp ?

### ISSUE THREAD

**Issue by perseval** [shaxxx/AltHttp#2]
I have an problem with dio headears, all is lowercase.

Following the this code : https://github.com/shaxxx/EnigmaWeb.Dart/blob/master/lib/src/web_requester.dart#L97

I try to initialize mine like this : 
 
```
  Dio _client() {
    
    var dio = Dio(); 

    dio.options.connectTimeout = timeout;
    dio.options.receiveTimeout = timeout; 
    (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
        (HttpClient client) {
      if (client == null || !(client is AltHttpClient)) {
        var altClient = AltHttpClient(); 
        return altClient;
      } 
      return client;
    }; 
    return dio;
  }
 
```
But when i send the post with headers, like this : 

 
```
dio = _client();
dio.options.headers =headers; 
response = await dio.post(
  Values.serverConfirm,
  data: formData, 
); 
```
 
The result is same than before implementing the package.

Where i'm wrong ?

**Comment by shaxxx** [comment]
What Dio version?
Have you seen this issue?
https://github.com/flutterchina/dio/issues/641

**Comment by perseval** [comment]
dio: ^3.0.9

Is the solution is to downgrade my dio to 3.0.7 ?

**Comment by shaxxx** [comment]
Yes, Dio 3.0.8 and higher forces all headers to lowercase.
Please request fix for this on the link I provided.
Clossing this since it's not AltHttp issue.

**Comment by perseval** [comment]
So my initialisation code was good !?
